### ISSUE TITLE
Constant defined incorrectly for year 2062, 1st and 2nd month.

### ISSUE THREAD

**Issue by aashishbaidya** [aerawatcorp/bikram#25]
The constant defined for the first 2 months in Bikram sambat seems to be incorrect for the year 2062 B.S. Which was converting the dates incorrectly.

Date conversion Issue:
![Screenshot from 2023-09-26 10-21-14](https://github.com/aerawatcorp/bikram/assets/20719868/d7e80c56-21e9-4a86-86f8-cb9df563a139)

Incorrect constant issue:
![Screenshot from 2023-09-26 10-11-18](https://github.com/aerawatcorp/bikram/assets/20719868/81db058d-d9a3-40ce-b05a-ce80151eda01)

Actual days in Baisakh and Jestha for year 2062 B.S.
![Screenshot from 2023-09-26 10-22-45](https://github.com/aerawatcorp/bikram/assets/20719868/33bf41ff-1e7b-4567-8f33-fc4ee29cb99b)

![Screenshot from 2023-09-26 10-22-59](https://github.com/aerawatcorp/bikram/assets/20719868/32c55bfc-5acb-40c4-8e38-9623712bae99)

**Comment by acpmasquerade** [comment]
Found some conflicting resources too
![image](https://github.com/aerawatcorp/bikram/assets/1309805/c6da1c6e-bb73-41d4-96b8-248bcd04e02d)

![Screenshot from 2024-06-17 22-30-00](https://github.com/aerawatcorp/bikram/assets/1309805/b7c69cc1-cdf4-4f60-b0ec-8822df8aa179)

reference - https://nepalicalendar.rat32.com/2062/jestha

**Comment by acpmasquerade** [comment]
even more 
![Screenshot from 2024-06-17 22-31-45](https://github.com/aerawatcorp/bikram/assets/1309805/b9ff846c-ed3a-4b96-87c3-d905ca74661b)

**Comment by acpmasquerade** [comment]
here is a printed version of asadh and shrawan of 2062
so its confirmed that Asar 01 is wednesday and 15th JUne

![image](https://github.com/aerawatcorp/bikram/assets/1309805/c1563c1d-0c4d-4cfe-a8a1-dd96d59780db)

**Comment by acpmasquerade** [comment]
As per the Nepal Rajpatra published on date 2062-Jestha-05
it indicates that the weekday is 05 - meaning Thursday, 

AS per this calculation, the first day should be on Sunday
![image](https://github.com/aerawatcorp/bikram/assets/1309805/115df068-195a-4659-99c2-315cd1e815ca)

**Comment by acpmasquerade** [comment]
Baisakh - 2062/01/05 is Monday
as per the Rajpatra

![image](https://github.com/aerawatcorp/bikram/assets/1309805/4d439a0a-0fdb-4ea5-bff8-6893cb06722a)


So considering all these, Baisakh and Jestha are considered to have 31 days in both months in Year 2062. 

![image](https://github.com/aerawatcorp/bikram/assets/1309805/39050341-48c3-4c35-be23-9b6e2614437f)
